dna = input("Please enter a valid DNA sequence: ")
lenght = len(dna)
num_a = dna.count('A')
num_c = dna.count('C')
num_g = dna.count('G')
num_t = dna.count('T')

print("The lenght of the DNA chain is: ", lenght)
print("Number of A's in the sequence: ", num_a)
print("Number of C's in the sequence: ", num_c)
print("Number of G's in the sequence: ", num_g)
print("Number of T's in the sequence: ", num_t)